insert into public.classes (
  id,
  host_id,
  title,
  weeks,
  total_spots,
  start_date,
  end_date,
  start_time,
  end_time,
  meeting_days,
  schedule_summary,
  location_details,
  description,
  image_url
) values (
  'c7f3a8e2-4b5d-4f9a-8c1e-2d3b4a5c6e7f',
  null,
  'Two Cents x Sundays: Tiny Talks!',
  1,
  null,
  '2026-04-12',
  '2026-04-12',
  '15:00',
  '17:00',
  'Sunday',
  'One-time event',
  'About Time — 3287 Wilshire Blvd B, Los Angeles, CA 90010',
  E'Two Cents Club is officially launching, and we want you there!!\n\nWe''re bringing together a room full of interesting people for a cozy afternoon, with a few brave souls sharing something they''ve been nerding out about lately. Short, informal, no-pressure presentations on whatever''s been keeping people up: a new skill, a rabbit hole they fell into at 2am, a creative project, a question they literally can''t stop thinking about.\n\nPresenting is totally optional. Come to share, come to listen, come because your friend dragged you and you''re glad they did.',
  '/images/Class-Assets/presentation-in-the-park.jpeg'
) on conflict (id) do update set
  title          = excluded.title,
  total_spots    = excluded.total_spots,
  start_date     = excluded.start_date,
  end_date       = excluded.end_date,
  start_time     = excluded.start_time,
  end_time       = excluded.end_time,
  meeting_days   = excluded.meeting_days,
  schedule_summary = excluded.schedule_summary,
  location_details = excluded.location_details,
  description    = excluded.description,
  image_url      = excluded.image_url;
